services:
  spark-master:
    build: .
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"   # Spark master
      - "8081:8080"   # Spark master UI
      - "4040:4040"   # Driver UI (khi chạy job từ master)
    volumes:
      - ./demo:/opt/app/demo
      - ./exercises:/opt/app/exercises
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks: [sparknet]

  spark-worker-1:
    build: .
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4G
    volumes:
      - ./demo:/opt/app/demo
      - ./exercises:/opt/app/exercises
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    depends_on: [spark-master]
    networks: [sparknet]

  

networks:
  sparknet:
    driver: bridge
